/**
 * KisanApp Marathi (मराठी) Copy Strings
 * Centralized dictionary for all farmer-facing app text.
 * Organized by module to keep screens clean and easy to maintain.
 */
export const STRINGS = {
  common: {
    appName: "लिनीअर शेती",
    welcome: "स्वागत आहे!",
    save: "जतन करा",
    cancel: "रद्द करा",
    back: "मागे",
    confirm: "नक्की करा",
    loading: "लोड होत आहे...",
    error: "काहीतरी चूक झाली. कृपया पुन्हा प्रयत्न करा.",
    noData: "माहिती उपलब्ध नाही",
    phone: "मोबाईल नंबर",
    submit: "प्रस्तुत करा",
    camera: "कॅमेरा वापरा",
    gallery: "गॅलरीमधून निवडा",
    removePhoto: "फोटो काढा",
    permissionDenied: "परवानगी नाकारली. कृपया सेटिंग्जमधून परवानग्या सुरू करा.",
    success: "यशस्वी",
    errorTitle: "त्रुटी"
  },
  nav: {
    home: "मुख्यपृष्ठ",
    cowshed: "माझा गोठा",
    marketplace: "बाजारपेठ",
    services: "शेतकरी सेवा",
    videos: "मार्गदर्शन व्हिडिओ",
    bullInfo: "वळू माहिती"
  },
  home: {
    quickTitle: "झटपट पर्याय",
    statsTitle: "📊 माझा गोठा सारांश",
    statsAnimals: "एकूण जनावरे",
    statsMilk: "दैनिक दूध उत्पादन",
    statsMilkVal: "३० लिटर",
    statsAnimalsVal: "५",
    warningTitle: "प्रोफाईल अपूर्ण आहे!",
    warningBody: "सर्व शेतकरी सेवांचा आणि बाजारपेठेचा लाभ घेण्यासाठी कृपया तुमची सविस्तर माहिती पूर्ण भरा.",
    warningBtn: "माहिती भरा (Complete Profile)",
    videoSubtitle: "तज्ञांचे मार्गदर्शन",
    videoDesc: "सेंद्रिय शेती, रोग व्यवस्थापन आणि आधुनिक तंत्रज्ञानाचे मार्गदर्शन व्हिडिओ पहा.",
    bullSubtitle: "सीमेन व पैदावर सुधार",
    bullDesc: "दर्जेदार सीमेन डोस, वळूंची वंशावळ आणि दूध वाढवण्यासंबंधी माहिती पहा.",
    profileTitle: "माझी प्रोफाईल",
    profileSubtitle: "वैयक्तिक व शेतीची माहिती",
    profileDesc: "तुमचे नाव, मोबाईल नंबर, गाव, आणि शेतीचे सविस्तर तपशील अपडेट करा."
  },
  cowshed: {
    title: "माझा गोठा",
    addCow: "नवीन जनावराची नोंद करा",
    cowName: "जनावराचे नाव / नंबर",
    breed: "जात (उदा. गीर, खिलार)",
    age: "वय (वर्षे)",
    milkYield: "दैनिक दूध (लिटर)",
    healthStatus: "आरोग्य स्थिती",
    healthy: "निरोगी",
    sick: "आजारी",
    milkTracker: "दूध नोंदणी",
    weightTracker: "वजन नोंदणी"
  },
  marketplace: {
    title: "बाजारपेठ",
    buySell: "खरेदी / विक्री",
    fodder: "चारा व पेंड",
    fertilizer: "खते व औषधे",
    price: "किंमत (₹)",
    seller: "विक्रेत्याचे नाव",
    contact: "संपर्क करा",
    uploadImage: "फोटो अपलोड करा",
    postListing: "जाहिरात टाका"
  },
  services: {
    title: "शेतकरी सेवा",
    tractor: "ट्रॅक्टर भाड्याने",
    drone: "ड्रोन फवारणी",
    labor: "शेतमजूर",
    pricePerHour: "दर प्रति तास (₹)",
    bookNow: "आत्ता बुक करा"
  },
  videos: {
    title: "मार्गदर्शन व्हिडिओ",
    addVideo: "नवीन व्हिडिओ जोडा",
    organicFarming: "सेंद्रिय शेती",
    cropDisease: "पीक रोग व्यवस्थापन",
    modernTech: "आधुनिक तंत्रज्ञान",

    // New strings for simplified UI
    subtitle: "शेती व गोठा व्यवस्थापनासाठी तज्ञांचे मोफत मार्गदर्शन",
    selectInfoType: "माहितीचा प्रकार निवडा",
    subjects: "विषय (Subjects)",
    subjectsSubtitle: "4 प्रमुख विषय व विभाग",
    subjectsDesc: "कृत्रिम रेतन, WWS, ABS आणि डेन्मार्क सीमेन संबंधित सविस्तर मार्गदर्शन.",

    experts: "मार्गदर्शक (Guides & Experts)",
    expertsSubtitle: "तज्ञ व अनुभवी वैज्ञानिक",
    expertsDesc: "कृषी विद्यापीठाचे प्राध्यापक, कृषी शास्त्रज्ञ आणि यशस्वी शेतकऱ्यांचे अनुभव व सल्ले.",

    companies: "संस्था व कंपन्या (Institutions)",
    companiesSubtitle: "शासकीय संस्था व कंपन्या",
    companiesDesc: "कृषी विभागाच्या योजना, सह्याद्री फार्म्स व कृषी विज्ञान केंद्रांचे अधिकृत व्हिडिओ.",

    selectSubject: "विषय निवडा",
    selectExpert: "मार्गदर्शक निवडा",
    selectCompany: "संस्था निवडा",
    selectDefault: "निवड करा",

    searchPlaceholder: "येथे शोधा...",
    videoSearchPlaceholder: "व्हिडिओ शोधा...",
    voiceSearchTitle: "कृषी व्हॉइस सर्च (Voice Search)",
    voiceSearchActive: "मराठी व्हॉइस असिस्टंट सुरू आहे...\nकृपया तुमच्या आवाजात सर्च करायचा शब्द बोला.",
    voiceSearchSpeakVideo: "मराठी व्हॉइस असिस्टंट सुरू आहे...\nकृपया तुमच्या आवाजात व्हिडिओचा विषय बोला.",
    voiceSearchCancel: "रद्द करा",
    voiceSearchOk: "ठीक आहे",
    voiceSearchNoMatch: "काही शब्द ओळखता आले नाहीत. कृपया लिहून शोधा.",
    voiceSearchResultTitle: "व्हॉइस सर्च परिणाम",

    videoListTitle: "मार्गदर्शन व्हिडिओ यादी",
    backBtn: "मागे",
    playerBackBtn: "मागे जा",
    videoInfoTitle: "व्हिडिओ माहिती:",
    durationLabel: "⏱️ ",
    minutesLabel: " मिनिटे",
    guideLabel: "👤 मार्गदर्शक:",
    subjectLabel: "📚 विषय:",
    companyLabel: "🏢 कंपनी/संस्था:",

    // Subject categories
    breedManagement: "पैदावर व्यवस्थापन",
    breedManagementDesc: "जातीवंत जनावरांची निवड, पैदावर आणि वंश सुधारणा",

    feedManagement: "चारा व खाद्य व्यवस्थापन",
    feedManagementDesc: "सकस पशुखाद्य, मुरघास (सायलेज) आणि चारा नियोजन",

    animalManagement: "जनावरांचे व्यवस्थापन",
    animalManagementDesc: "गोठा स्वच्छता, आरोग्य आणि दूध उत्पादन वाढ",

    organicFarmingDesc: "विषमुक्त शेती, कंपोस्ट खत आणि सेंद्रिय औषध फवारणी",
    cropDiseaseDesc: "पिकांवरील रोग नियंत्रण आणि जैविक कीटकनाशके",
    modernTechDesc: "ड्रोन फवारणी, आधुनिक यंत्रे आणि स्मार्ट शेती पद्धती",

    semenInfo: "सीमेन माहिती",
    semenInfoDesc: "कृत्रिम रेतन आणि दर्जेदार सीमेन संबंधी संपूर्ण माहिती",
    wwsSemen: "WWS सीमेन",
    wwsSemenDesc: "WWS (World Wide Sires) सीमेन द्वारे पैदावर व वंश सुधारणा",
    absSemen: "ABS सीमेन",
    absSemenDesc: "ABS सीमेन तंत्रज्ञान आणि जनावरांची दूध उत्पादकता वाढ",
    denmarkSemen: "DENMARK सीमेन",
    denmarkSemenDesc: "डेन्मार्क सीमेनचे उपयोग आणि संकरित पैदावर नियोजन",

    // Add Video Form strings
    saveSuccess: "व्हिडिओ यशस्वीरीत्या जतन केला आहे.",
    saveError: "व्हिडिओ जतन करताना त्रुटी आली. कृपया पुन्हा प्रयत्न करा.",
    formTitleLabel: "व्हिडिओचे शीर्षक (Video Title)",
    formTitlePlaceholder: "उदा. अधिक दुधासाठी गोठा व्यवस्थापन",
    formVideoUrlLabel: "यूट्यूब व्हिडिओ लिंक (YouTube URL)",
    formVideoUrlPlaceholder: "उदा. https://www.youtube.com/watch?v=...",
    formSubjectLabel: "विषय / श्रेणी (Subject / Category)",
    formSubjectPlaceholder: "श्रेणी निवडा...",
    formAuthorLabel: "मार्गदर्शक (Expert / Guide)",
    formAuthorPlaceholder: "उदा. डॉ. हरीश माने",
    formCompanyLabel: "संस्था / कंपनी (Institution)",
    formCompanyPlaceholder: "उदा. सह्याद्री फार्म",
    formDurationLabel: "कालावधी (Duration)",
    formDurationPlaceholder: "उदा. 05:20",
    formDescriptionLabel: "व्हिडिओचे सविस्तर वर्णन (Description)",
    formDescriptionPlaceholder: "व्हिडिओबद्दल माहिती लिहा...",
    loadingYoutubeMetadata: "यूट्यूब व्हिडिओची माहिती मिळवत आहे...",
    youtubeFetchError: "यूट्यूब व्हिडिओची माहिती मिळू शकली नाही. कृपया मॅन्युअली माहिती भरा."
  },
  auth: {
    login: "लॉगिन करा",
    otpSent: "तुमच्या मोबाईलवर ओटीपी (OTP) पाठवला आहे",
    verifyOtp: "ओटीपी सत्यापित करा",
    enterPhone: "तुमचा 10 अंकी मोबाईल नंबर टाका",
    otpRequestError: "ओटीपी पाठवताना त्रुटी आली. कृपया पुन्हा प्रयत्न करा किंवा चाचणीसाठी मॉक मोड वापरा.",
    enterCorrectOtp: "कृपया अचूक 6 अंकी ओटीपी कोड प्रविष्ट करा.",
    otpVerificationFailed: "ओटीपी पडताळणी अयशस्वी. कृपया अचूक कोड टाका.",
    sendOtp: "ओटीपी (OTP) पाठवा",
    phoneNumberLabel: "नंबर",
    enterOtpLabel: "6-अंकी ओटीपी (OTP) प्रविष्ट करा",
    otpPlaceholder: "उदा. 123456",
    backBtn: "मागे जा",
    userBlocked: "तुमचे खाते ब्लॉक केले आहे. कृपया ॲडमिनशी संपर्क साधा.",
    userInactive: "तुमचे खाते सक्रिय नाही. कृपया ॲडमिनशी संपर्क साधा.",
    googleLogin: "गुगल द्वारे सुरू करा",
    videoFeatureTitle: "तज्ञांचे मार्गदर्शन व्हिडिओ",
    videoFeatureDesc: "शेती, गोठा आणि आधुनिक तंत्रज्ञानाविषयी तज्ञांचे विनामूल्य मार्गदर्शन व्हिडिओ पहा.",
    nameLabel: "शेतकऱ्याचे पूर्ण नाव",
    namePlaceholder: "उदा. रामराव गायकवाड",
    phoneLabel: "मोबाईल नंबर (अनिवार्य)",
    phonePlaceholder: "उदा. ९८७६५४३२१०",
    googleError: "गुगल लॉगिन यशस्वी झाले नाही. कृपया पुन्हा प्रयत्न करा.",
    onboardingWelcome: "शेतकरी नावनोंदणी व लॉगिन"
  },
  splash: {
    tagline: "प्रगतीशील शेतकऱ्यांचे डिजिटल व्यासपीठ",
    loadingApp: "ॲप सुरू होत आहे..."
  },
  profile: {
    personalInfo: "वैयक्तिक माहिती",
    nameLabel: "शेतकऱ्याचे पूर्ण नाव",
    namePlaceholder: "उदा. रामराव गायकवाड",
    phonePlaceholder: "उदा. 9876543210",
    roleLabel: "भूमिका निवडा",
    buyer: "खरेदीदार",
    seller: "विक्रेता",
    both: "दोन्ही",
    addressTitle: "पत्ता (सोलापूर जिल्हा विशेष)",
    districtLabel: "जिल्हा",
    solapur: "सोलापूर",
    selectTaluka: "तालुका निवडा",
    talukaPlaceholder: "तालुका निवडण्यासाठी येथे दाबा...",
    selectVillage: "गाव निवडा",
    villagePlaceholder: "गाव निवडण्यासाठी येथे दाबा...",
    selectTalukaFirst: "आधी तालुका निवडा...",
    pincodeLabel: "पिनकोड (Pincode)",
    pincodePlaceholder: "उदा. 413001",
    mapSelectTitle: "नकाशावरून शेतीचे ठिकाण निवडा",
    mapSelectSub: "नकाशात तुमच्या शेताच्या जागेवर टॅप करा. अचूक स्थान मिळवले जाईल:",
    latitude: "अक्षांश",
    longitude: "रेखांश",
    farmDetailsTitle: "शेतीचे सविस्तर तपशील",
    totalAreaLabel: "एकूण शेत जमीन (एकर)",
    totalAreaPlaceholder: "उदा. 10",
    cultivatedAreaLabel: "लागवडीखालील/वापरात असलेले क्षेत्र (एकर)",
    cultivatedAreaPlaceholder: "उदा. 8",
    mainCropLabel: "मुख्य पिके",
    mainCropPlaceholder: "उदा. ऊस, कांदा, डाळिंब",
    logoutBtn: "लॉगआउट करा (Logout)",
    logoutConfirmTitle: "तुम्हाला नक्की लॉगआउट करायचे आहे का?",
    logoutConfirmBtn: "लॉगआउट करा",
    gpsSuccessMsg: "जीपीएस (GPS) उपग्रहाद्वारे अचूक स्थान प्राप्त झाले!",
    saveSuccess: "तुमची प्रोफाईल यशस्वीरीत्या जतन केली आहे.",
    saveError: "माहिती जतन करताना त्रुटी आली. कृपया पुन्हा प्रयत्न करा.",
    logoutError: "लॉगआउट करताना त्रुटी आली.",
    ratingLabel: "रेटिंग",
    activeFarmer: "सक्रिय शेतकरी"
  },
  bullInfo: {
    title: "वळू व सीमेन माहिती",
    subtitle: "उत्कृष्ट पैदावर आणि वंशावळ सुधारण्यासाठी दर्जेदार सीमेन",
    semenBrandsTitle: "सीमेन ब्रँड यादी",
    semenBrandsSubtitle: "पैदावर सुधारणेसाठी दर्जेदार ब्रँड्स",
    addBrand: "नवीन ब्रँड जोडा",
    brandNameLabel: "ब्रँडचे नाव",
    brandNamePlaceholder: "उदा. ABS Semen, WWS Semen",
    logoUrlLabel: "लोगो प्रतिमा (Select Logo)",
    logoUrlPlaceholder: "कॅмера किंवा गॅलरीमधून लोगो निवडा",
    logoSelected: "लोगो प्रतिमा निवडली आहे",
    saveBrandBtn: "ब्रँड जतन करा",
    saveBrandSuccess: "नवीन सीमेन ब्रँड यशस्वीरीत्या जतन केला आहे.",
    saveBrandError: "ब्रँड जतन करताना त्रुटी आली. कृपया पुन्हा प्रयत्न करा.",
    editBrand: "सीमेन ब्रँड सुधारा",
    updateBrandSuccess: "सीमेन ब्रँड यशस्वीरीत्या सुधारला आहे.",
    updateBrandError: "ब्रँड सुधारताना त्रुटी आली. कृपया पुन्हा प्रयत्न करा.",
    deleteBrandConfirmTitle: "ब्रँड काढा",
    deleteBrandConfirmDesc: "तुम्हाला नक्की हा सीमेन ब्रँड काढायचा आहे का?",
    deleteBrandSuccess: "सीमेन ब्रँड यशस्वीरीत्या काढला आहे.",
    deleteBrandError: "ब्रँड काढताना त्रुटी आली. कृपया पुन्हा प्रयत्न करा.",
    brandNameRequired: "ब्रँडचे नाव आवश्यक आहे.",
    brandNameMin: "नाव किमान २ अक्षरी असावे.",
    brandNameMax: "नाव ५० अक्षरांपेक्षा जास्त नसावे.",
    logoUrlInvalid: "कृपया वैध इमेज फाईल निवडा.",
    activeStatus: "सक्रिय (Active)",
    rosterTitleSuffix: "लाईनअप",
    searchBullPlaceholder: "नाव किंवा NAAB कोडने वळू शोधा...",
    breedAll: "सर्व जाती",
    filterBtn: "फिल्टर",
    addBull: "नवीन वळू नोंदवा",
    editBull: "वळू माहिती सुधारा",
    saveBullBtn: "वळू जतन करा",
    saveBullSuccess: "नवीन वळू यशस्वीरीत्या जतन केला आहे.",
    saveBullError: "वळू जतन करताना त्रुटी आली. कृपया पुन्हा प्रयत्न करा.",
    updateBullSuccess: "वळू माहिती यशस्वीरीत्या जतन केली आहे.",
    updateBullError: "वळू माहिती जतन करताना त्रुटी आली. कृपया पुन्हा प्रयत्न करा.",
    basicInfoSection: "१. प्राथमिक माहिती (Basic Info)",
    pedigreeSection: "२. वंशावळ (Pedigree)",
    realWorldDataSection: "३. वास्तववादी डेटा (Real World Data)",
    cdcbStatsSection: "४. CDCB आकडेवारी (CDCB Stats)",
    bullNameLabel: "वळूचे नाव (Bull Name)",
    bullNamePlaceholder: "उदा. ABS Jeronimo",
    naabCodeLabel: "NAAB कोड",
    naabCodePlaceholder: "उदा. 29HO18817",
    regNoLabel: "नोंदणी क्रमांक (Reg No)",
    regNoPlaceholder: "उदा. HO840003131003289",
    tpiLabel: "TPI (Total Performance Index)",
    tpiPlaceholder: "उदा. 2750",
    breedLabelForm: "जात (Breed)",
    breedPlaceholderForm: "उदा. Holstein-Friesian, Jersey, Gir",
    photoUrlLabel: "फोटो URL (पर्यायी)",
    photoUrlPlaceholder: "उदा. https://...",
    photoUrlsLabel: "वळूचे फोटो (Select Photos)",
    photoUrlsPlaceholder: "कॅमेरा किंवा गॅलरीमधून वळूचे फोटो निवडा.",
    selectImagesBtn: "फोटो निवडा",
    cameraOption: "कॅमेरा द्वारे फोटो काढा",
    galleryOption: "गॅलरी मधून निवडा",
    maxImagesAlert: "तुम्ही जास्तीत जास्त ५ फोटो निवडू शकता.",
    photoRequiredError: "वळूचा किमान १ फोटो निवडणे आवश्यक आहे.",
    uploadingImages: "माहिती आणि फोटो अपलोड होत आहेत...",
    cdcbSheetTitle: "CDCB डेटा पत्रक",
    bookingTitle: "सीमेन डोस बुकिंग",
    sireLabel: "वडिलांचे नाव (Sire)",
    sirePlaceholder: "उदा. De-Su 13050 Spectre",
    damSireLabel: "आईचे वडील (Dam's Sire)",
    damSirePlaceholder: "उदा. Mr Mogul Delta 1427",
    mgsLabel: "MGS (Maternal Grand Sire)",
    mgsPlaceholder: "उदा. Delta MGS",
    mgdLabel: "MGD (Maternal Grand Dam)",
    mgdPlaceholder: "उदा. Goldwyn MGD",
    mggsLabel: "MGGS (Maternal Great Grand Sire)",
    mggsPlaceholder: "उदा. Oman MGGS",
    productionTitle: "CDCB उत्पादन आकडेवारी",
    milkLbsLabel: "दूध वाढ (Milk Lbs)",
    milkKgLabel: "दूध वाढ (Milk Kg)",
    fatLbsLabel: "फॅट वाढ (Fat Lbs)",
    fatPercentLabel: "फॅट टक्केवारी (%)",
    proteinLbsLabel: "प्रोटिन वाढ (Protein Lbs)",
    proteinPercentLabel: "प्रोटिन टक्केवारी (%)",
    combinedFatProteinLabel: "एकूण फॅट व प्रोटीन (CFP)",
    combinedFatProteinPlaceholder: "उदा. १२०",
    reliabilityAbbr: "Rel (%)",
    fertilityTitle: "गर्भधारणा व प्रजनन (Fertility)",
    calvingTitle: "विण्याचे गुणधर्म (Calving Traits)",
    calvingTraitHeader: "विण्याचे गुणधर्म (Trait)",
    valueHeader: "मूल्य (Value)",
    healthTitle: "आरोग्य आकडेवारी",
    productiveLifeLabel: "उत्पादक आयुष्य (Productive Life)",
    dprLabel: "लेकीचा गर्भधारणा दर (DPR)",
    scrLabel: "वळूचा गर्भधारणा दर (SCR)",
    scrPlaceholder: "उदा. १.५",
    hcrLabel: "कालवडींचा गर्भधारणा दर (HCR)",
    hcrPlaceholder: "उदा. 1.2",
    ccrLabel: "गाईंचा गर्भधारणा दर (CCR)",
    ccrPlaceholder: "उदा. 0.5",
    betaCaseinLabel: "बीटा केसिन (Beta Casein)",
    betaCaseinPlaceholder: "उदा. A2A2",
    transitionRightLabel: "Transition Right",
    transitionRightPlaceholder: "स्टार रेटिंग निवडा (१ ते ५)",
    cdcbLabel: "CDCB",
    scsLabel: "सोमॅटिक सेल स्कोर (SCS)",
    mastLabel: "MAST (मास्टायटीस)",
    metrLabel: "METR (मेट्रायटीस)",
    ketoLabel: "KETO (किटोसिस)",
    replLabel: "REPL (रिटेन्ड प्लेसेंटा)",
    dsabLabel: "DSAB (डिस्प्लेस्ड ॲबोमेझम)",
    mfevLabel: "MFEV (मिल्क फिव्हर)",
    healthExplTitle: "💡 आरोग्य स्कोअरचे स्पष्टीकरण (ट्रेड स्कोअर +३.० असल्यास):",
    mastExplanation: "त्याच्या मुलींना (गाईंना) मळस/दगडी होण्याचा धोका सरासरीपेक्षा ३.०% कमी असेल.",
    metrExplanation: "विल्यानंतर गर्भाशयाची सूज किंवा इन्फेक्शन होण्याचा धोका ३.०% कमी असेल.",
    ketoExplanation: "शरीरातील ऊर्जा कमी पडून किटोसिस आजार होण्याचा धोका ३.०% कमी असेल.",
    replExplanation: "विल्यानंतर वार (जाळ) अडकण्याची शक्यता ३.०% कमी असेल.",
    dsabExplanation: "चौथे पोट सरकण्याचा गंभीर आजार होण्याचा धोका ३.०% कमी असेल.",
    mfevExplanation: "कॅल्शियम कमी पडून मिल्क फिव्हर (दुग्धज्वर) होण्याचा धोका ३.०% कमी असेल.",
    sceLabel: "सहज जन्माचे प्रमाण (SCE)",
    scePlaceholder: "उदा. 1.9",
    dceLabel: "लेकींच्या जन्मातील सहजता (DCE)",
    dcePlaceholder: "उदा. 2.1",
    ssbLabel: "वळू मृत्यूदर (SSB)",
    ssbPlaceholder: "उदा. 5.5",
    dsbLabel: "लेकींचा मृत्यूदर (DSB)",
    dsbPlaceholder: "उदा. 6.2",
    conformationTitle: "शरीररचना (Conformation)",
    ptatLabel: "PTAT",
    udcLabel: "कास रचना (UDC)",
    flcLabel: "पाय रचना (FLC)",
    bwcLabel: "शरीर वजन निर्देशांक (BWC)",
    bwcPlaceholder: "उदा. 0.85",
    statureTitle: "शरीर वजन रचना (Body Weight)",
    feetLegsTitle: "पाय आणि खूर रचना (Feet & Legs)",
    udderTitle: "कास रचना (Udder)",
    teatPlacementTitle: "सडांची ठेवण (Teat Placement)",
    statureLabel: "उंची/बांधा (Stature)",
    strengthLabel: "छातीची रुंदी (Strength)",
    bodyDepthLabel: "शरीराची खोली (Body Depth)",
    dairyFormLabel: "दुग्ध गुण वैशिष्ट्ये (Dairy Form)",
    rumpAngleLabel: "पुठ्ठ्याचा कोन (Rump Angle)",
    thurlWidthLabel: "खुब्याची रुंदी (Thurl Width)",
    rearLegsSideViewLabel: "मागील बाजूने पाय (Rear Legs Side View)",
    rearLegsRearViewLabel: "मागील पाठीमागून पाय (Rear Legs Rear View)",
    footAngleLabel: "खुराचा कोन (Foot Angle)",
    feetLegsScoreLabel: "पाय आणि खुरांचा स्कोर (Feet & Legs Score)",
    foreUdderAttachmentLabel: "कासेची शरीराशी जोडणी (Fore Udder Attachment)",
    rearUdderHeightLabel: "मागील कासेची उंची (Rear Udder Height)",
    rearUdderWidthLabel: "मागील कासेची रुंदी (Rear Udder Width)",
    udderCleftLabel: "कासेची मधली रेघ (Udder Cleft)",
    udderDepthLabel: "कासेची खोली (Udder Depth)",
    frontTeatPlacementLabel: "पुढील सडांची ठेवण (Front Teat Placement)",
    rearTeatPlacementLabel: "मागील सडांची ठेवण (Rear Teat Placement)",
    teatLengthLabel: "सडांची लांबी (Teat Length)",
    conformationPlaceholder: "उदा. १.२०",
    evalDateLabel: "चाचणी तारीख",
    evalDatePlaceholder: "उदा. June 2026",
    brandAll: "सर्व ब्रँड",
    brandWws: "WWS सीमेन",
    brandAbs: "ABS सीमेन",
    brandDenmark: "डेन्मार्क",
    breedLabel: "जात (Breed):",
    damMilkLabel: "आईचे दूध:",
    fatLabel: "फॅट प्रमाण:",
    conceptionLabel: "गर्भधारणा दर:",
    priceLabel: "किंमत (प्रति डोस):",
    detailsBtn: "मार्गदर्शन व्हिडिओ",
    inquiryBtn: "डोस बुक करा",
    inquirySuccess: "तुमची चौकशी यशस्वीरीत्या नोंदवली गेली आहे. आमचे प्रतिनिधी लवकरच संपर्क करतील.",
    contactTitle: "डोस बुकिंग व चौकशी",
    contactInfo: "सीमेन डोस बुकिंगसाठी खालील नंबरवर संपर्क साधा किंवा व्हॉट्सॲप मेसेज करा:\n\nसंपर्क: +91 98765 43210\nवेळ: सकाळी ९ ते संध्याकाळी ६",
    noBulls: "या श्रेणीत वळू उपलब्ध नाहीत.",
    bulkEditBtn: "एकत्रित दूध वाढ सुधारा (Bulk Edit Milk)",
    bulkEditTitle: "दूध वाढ एकत्रित बदला (Bulk Edit Milk Lbs)",
    quickSetLabel: "सर्व वळूंसाठी एकत्र सेट करा",
    quickSetPlaceholder: "उदा. १२५०",
    applyToAllBtn: "लागू करा",
    saveAllBtn: "सर्व बदल जतन करा",
    bulkUpdateSuccess: "सर्व वळूंची दूध वाढ यशस्वीरीत्या अपडेट केली आहे.",
    bulkUpdateError: "दूध वाढ अपडेट करताना त्रुटी आली. कृपया पुन्हा प्रयत्न करा.",
    bulkUpdateNoBulls: "अपडेट करण्यासाठी वळू उपलब्ध नाहीत.",
    wwsDesc: "World Wide Sires (USA) कडून आयात केलेले उच्च गुणवत्तेचे सीमेन.",
    absDesc: "ABS India द्वारे जनुक क्षमता वाढवण्यासाठी आणि दुधाळ जनावरांच्या पैदाशीसाठी विशेष डोस.",
    denmarkDesc: "डेन्मार्क सरकार आणि सहकार संस्थांद्वारे विकसित उच्च दूध उत्पादक वंश.",
    searchPlaceholder: "वळू किंवा जात शोधा...",
    bookSuccessTitle: "यशस्वी नोंदणी",
    bulls: [
      {
        id: "1",
        name: "ABS रॅम्बो (Rambo)",
        code: "29GR891",
        breed: "गीर (Gir)",
        brand: "abs",
        damMilk: "१२,५०० लिटर",
        fat: "४.७%",
        conception: "उत्कृष्ट (High)",
        price: "₹३५०",
        image: "https://images.unsplash.com/photo-1596733430284-f7437764b1a9?q=80&w=600",
        description: "शुद्ध गीर वंशाचा वळू. उच्च दुग्ध उत्पादक आईचे गुणधर्म आणि उत्तम शरीररचना.",
        videoCategory: "abs_semen"
      },
      {
        id: "2",
        name: "WWS बस्टर (Buster)",
        code: "7HO1234",
        breed: "एचएफ (HF)",
        brand: "wws",
        damMilk: "१५,८०० लिटर",
        fat: "३.८%",
        conception: "उत्कृष्ट (High)",
        price: "₹५००",
        image: "https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?q=80&w=600",
        description: "अमेरिकन वंशावळीचा उच्च दर्जाचा एचएफ वळू. कालवडींमध्ये उच्च दुग्ध क्षमता हस्तांतरण.",
        videoCategory: "wws_semen"
      },
      {
        id: "3",
        name: "डेन्मार्क थोर (Thor)",
        code: "DK3391",
        breed: "एचएफ (HF)",
        brand: "denmark",
        damMilk: "१४,२०० लिटर",
        fat: "४.०%",
        conception: "मध्यम (Medium)",
        price: "₹४५०",
        image: "https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?q=80&w=600",
        description: "डेन्मार्कवरून आयात केलेल्या सीमेनचे उच्च श्रेणीचे गुणधर्म, अधिक प्रतिकारशक्ती.",
        videoCategory: "denmark_semen"
      },
      {
        id: "4",
        name: "ABS टायटन (Titan)",
        code: "29HO773",
        breed: "एचएफ (HF)",
        brand: "abs",
        damMilk: "१३,९०० लिटर",
        fat: "३.९%",
        conception: "उत्कृष्ट (High)",
        price: "₹४००",
        image: "https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?q=80&w=600",
        description: "दुधाळ गाई पैदास करण्यासाठी आणि कालवडींचा जलद विकास करण्यासाठी ABS का सर्वोत्तम वळू.",
        videoCategory: "abs_semen"
      },
      {
        id: "5",
        name: "WWS मॅव्हरिक (Maverick)",
        code: "7JE5678",
        breed: "जर्सी (Jersey)",
        brand: "wws",
        damMilk: "१०,२०० लिटर",
        fat: "५.१%",
        conception: "उत्कृष्ट (High)",
        price: "₹४८०",
        image: "https://images.unsplash.com/photo-1484557985045-edd9d294d5d4?q=80&w=600",
        description: "जर्सी वंशाचा उत्कृष्ट वळू, दुधातील फॅट आणि एसएनएफ वाढवण्यासाठी प्रसिद्ध.",
        videoCategory: "wws_semen"
      },
      {
        id: "6",
        name: "खिलार अर्जुन (Arjun)",
        code: "KH9921",
        breed: "खिलार (Khillar)",
        brand: "abs",
        damMilk: "२,५०० लिटर",
        fat: "४.५%",
        conception: "उत्कृष्ट (High)",
        price: "₹३००",
        image: "https://images.unsplash.com/photo-1527153857715-3908f2bac5e8?q=80&w=600",
        description: "खिलार जातीचा अस्सल आणि मजबूत वळू, शेती कामासाठी चपळ बैल पैदास करण्यासाठी योग्य.",
        videoCategory: "semen_info"
      }
    ]
  }
};
